Save codable models
icapps/ios-stella pull request #64
Opened 2019-03-17 01:34 UTC by AdamsDevelopment

2019-03-17 06:05 UTC, fousa requested changes
Voeg je nog info toe aan de README? Ziet er goed uit voor de rest!

2019-03-17 20:50 UTC, AdamsDevelopment commented
> Voeg je nog info toe aan de README? Ziet er goed uit voor de rest!

README toegevoegd, slightly different dan de rest. Omdat ik het ook met een klein voorbeeld wilde tonen zodat het meer relevant was.

2019-03-18 05:42 UTC, fousa requested changes
Kan het zijn dat de testen falen?

2019-03-18 05:42 UTC, fousa commented on README.md
> +### Codable Defaults
Enkel dit nog in de inhoudstabel toevoegen :)

2019-05-09 13:51 UTC, AdamsDevelopment commented
> @AdamsDevelopment, wat is de status van dit?

Testen falen, een Bool is Codable waardoor er foute interpretatie's ontstaan wanneer je iets saved als codable model of bool. Eens ik een moment tijd vind ga ik dit oplossen. :)

2025-05-03 22:36 UTC, closed without merging